# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 7dc2d1a119bf4d71b03da8d80aa8f701e649a8b68f6c072fb30223a24e2c9fb2ac59bc56f730497816dc8e608dad79432de137cdbc210d25b021f0fd93a78731

test:
  domain_name: example.com 
  secret_key_base: 17660b3ba9d8ffe2efb728024031cd545e7937be725f7ef783d5117ce4b80f06ef57467729c090f7ab3c6afff1fdfcc3c3e7b2b388f0c7fbac5c0814fc2a3182

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  #admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_name: First User
  #admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_email: user@example.com
  #admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  admin_password: changeme
  #domain_name: <%= ENV["DOMAIN_NAME"] %>
  domain_name: aqueous-journey-6933.herokuapp.com
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 7dc2d1a119bf4d71b03da8d80aa8f701e649a8b68f6c072fb30223a24e2c9fb2ac59bc56f730497816dc8e608dad79432de137cdbc210d25b021f0fd93a78731